name: Build and Pin to IPFS

on:
  push:
    branches: [website]
  pull_request:
    branches: [website]

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_pin:
    runs-on: ubuntu-latest
    name: Build and Pin to IPFS
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build ${{ vars.IPFS_BUILD_MODE || 'sepolia' }}
        env:
          PUBLIC_NODE_URL: ${{ vars.PUBLIC_NODE_URL }}
          PUBLIC_CHAIN_INFO_NODE_URL: ${{ vars.PUBLIC_CHAIN_INFO_NODE_URL }}
          PUBLIC_ENS_NODE_URL: ${{ vars.PUBLIC_ENS_NODE_URL }}

      - name: IPFS publishing, pinning and IPNS update
        id: pinata
        uses: ./.github/actions/pinata-upload
        with:
          pinata-jwt: ${{ secrets.PINATA_JWT }}
          build-location: "./web/build"
          pin-alias: "${{ github.event.repository.name }}-${{ github.event_name == 'pull_request' && format('pull_request_{0}', github.head_ref) || 'main' }}"
          cid-version: "1"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ipns-name: ${{ vars.FILEBASE_NAME_LABEL }}
          filebase-access-key: ${{ secrets.FILEBASE_ROOT_ACCESS_KEY }}
          filebase-secret-key: ${{ secrets.FILEBASE_ROOT_SECRET_KEY }}
