name: Build and Pin to IPFS

on:
  push:
    branches: [website]
  pull_request:
    branches: [website]

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_pin:
    runs-on: ubuntu-latest
    name: Build and Pin to IPFS
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build ${{ vars.IPFS_BUILD_MODE || 'sepolia' }}
        env:
          PUBLIC_NODE_URL: ${{ vars.PUBLIC_NODE_URL }}
          PUBLIC_ENS_NODE_URL: ${{ vars.PUBLIC_ENS_NODE_URL }}
          PUBLIC_FAUCET_LINK: ${{ vars.PUBLIC_FAUCET_LINK }}

      - name: Deploy to IPFS
        id: deploy
        if: github.event_name != 'pull_request'
        uses: wighawag/pinnace/actions/deploy@main
        with:
          endpoint: https://ipfs-publisher.ska.sh
          site: jolly-roger-staging
          mode: ipfs
          dir: web/build
          promote-to: jolly-roger.eth
        env:
          PINNACE_HOST_PUBLISHER_TOKEN: ${{ secrets.PINNACE_HOST_PUBLISHER_TOKEN }}
